### ISSUE TITLE
BlockType, enums, IDs and mods.

### ISSUE THREAD

**Issue by Flosus** [bleroy/minecraft.client#16]
Let's talk about enums first.

The current implementation uses an enum for differentiate block types. This prevents adding new Blocks added from mods. While the current implementation supports modded blocks by declaring them as UnknownBlocks it will stop working if the server uses to many mods, because the IDs get parsed as byte. 

Let's talk about IDs next

I know that the use of BlockIDs comes from the way the raspberryjammod is [made](https://github.com/arpruss/raspberryjammod/blob/master/src/main/java/mobi/omegacentauri/raspberryjammod/APIHandler.java#L255). I want to raise the attention to the fact that this is not the way minecraft (and forge) are handling block (and item) registration. They use unique item and block names to register them. The problem with IDs is, that they can change from gameworld to gameworld. IDs have to get handled out separately for every connection. On one server an ID can be a IronChest, on an other server it could be a BuildCraft pipe.

I hope i could show my concerns. I'm currently thinking about a ways to solve this problem. I wanted to raise attention to this problem now, because we are in an early state and I want to avoid having a big problem later on.

**Comment by Flosus** [comment]
Things I think we have to do:

- Change the use of [BlockIDs](http://minecraft.gamepedia.com/Data_values#Block_IDs) to the names of blocks.
- Build a registry to register blocks (and later items), which handles the mapping of the objects and IDs with the use of names rather than initializing the objects with hard coded IDs.

**Comment by bleroy** [comment]
OK, sounds like this will be better done early, yes.

**Comment by bleroy** [comment]
I've been thinking a bit more about this. The thing that's bothering me the most is that our blocks currently are tied to the Java implementation, whereas they should be pure data structures, and their type should be defined by... their type. You make a great point about mods, of course, but I'd still want to kick that enum out. I also want to keep the ceremony associated with creating a block type to a minimum: if we project ourselves into the future where we can also interact with Minecraft for Windows 10, we don't want block authors to have to write too much code (if any) for each of the providers. Lots to think about...
