### ISSUE TITLE
How long do you want to support VS 2015?

### ISSUE THREAD

**Issue by Petermarcu** [bleroy/minecraft.client#18]
I have the changes to migrate merge here: https://github.com/petermarcu/minecraft.client

I can make a PR into master or into a branch. Hopefully we don't let them diverge for too long though. The Msbuild solution based on VS 2017 RC is working well for me.

**Comment by bleroy** [comment]
I'd prefer to have those changes in a separate branch if that's ok, until 2017 is RTM. Does this make sense?

**Comment by Petermarcu** [comment]
If thats what you want. The tooling is RC either way :) So as I make changes to add blocks do you want me to make changes in that branch?

**Comment by bleroy** [comment]
It shouldn't change the project file in either branch, so it should be easy enough to merge. I think. Let's try it, and if it proves too cumbersome, we can revise.

**Comment by Petermarcu** [comment]
Ok, I'll make the PR

**Comment by bleroy** [comment]
Thanks!

**Comment by Petermarcu** [comment]
Can you create a branch in your repo called msbuild?

**Comment by bleroy** [comment]
Yup. https://github.com/bleroy/minecraft.client/tree/msbuild

**Comment by bleroy** [comment]
msbuild was merged into master. The project now requires preview 3 tooling.
